# Generated by Django 6.0.8 on 2026-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
