# Generated by Django 6.0.7 on 2026-08-13 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_weight', models.IntegerField()),
                ('midterm_score', models.FloatField(blank=True, null=True)),
                ('assignments_weight', models.IntegerField()),
                ('final_weight', models.IntegerField()),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
